### ISSUE TITLE
Bug: request_meta is not available in server.request_context

### ISSUE THREAD

**Issue by phact** [modelcontextprotocol/python-sdk#103]
**Describe the bug**
This makes it impossible to build a server with progress notifications

**To Reproduce**
do a tool_call for example:

{
  "method": "tools/call",
  "params": {
    "name": "6a41a978-0a31-4eaf-9d0c-431a5f784bc9",
    "arguments": {
      "input_value": "3*2"
    },
    "_meta": {
      "progressToken": 0
    }
  }
}

server.request_context.meta is None

**Expected behavior**
meta should include the progressToken

It's not getting assigned here https://github.com/modelcontextprotocol/python-sdk/blob/main/src/mcp/server/__init__.py#L447

**Comment by dsp-ant** [comment]
Good catch. Do you mind having a go at create a PR? Happy to review.
