### ISSUE TITLE
Discrepancy in documentation for resource templates

### ISSUE THREAD

**Issue by maledorak** [modelcontextprotocol/python-sdk#68]
In 5th step of [python sdk advanced features](https://modelcontextprotocol.io/docs/first-server/python#advanced-features) there is explanation how to use resource templates

```
@self.list_resources()
async def list_resources(self) -> ListResourcesResult:
    return ListResourcesResult(
        resources=[...],
        resourceTemplates=[
            ResourceTemplate(
                uriTemplate="weather://{city}/current",
                name="Current weather for any city",
                mimeType="application/json"
            )
        ]
    )
```

Which is wrong because `ListResourcesResult` does not accept `resourceTemplates`
[ListResourcesResult implementation](https://github.com/modelcontextprotocol/python-sdk/blob/91b255f83f9790e924becc5854dc33265cf4bead/src/mcp/types.py#L379)

Also there is no option to use `ListResourceTemplatesResult` separately, because there is no `Server.list_resource_templates` in order to use it as decorator

**Comment by dsp-ant** [comment]
Thanks for reporting this! I'll prioritize this. It's clearly that the SDK is missing this.
