### ISSUE TITLE
Do we need to have mac  or windows compulsory for this or this will work in linux?

### ISSUE THREAD

**Issue by hemangjoshi37a** [modelcontextprotocol/python-sdk#81]
because the claude app is only available for the mac and windows.

**Comment by dsp-ant** [comment]
Note that MCP is an open protocol. Claude Desktop is just one client of many and people are actively working on building MCP clients into more products. Sourcegraph's Cody and Zed Editor both support MCP and work on Linux. There are limitations in both implementations, but I Am sure they will improve. For testing and development purposes, the inspector http://github.com/modelcontextprotocol/inspector works on Linux and can be used to build MCP servers on Linux.
